name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Set up node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 14 # Latest LTS
      - name: Install dependencies
        run: npm i
      - name: Lint (JavaScript)
        run: npm run lint:eslint
